#!/usr/bin/env node
/**
 * generate-version.mjs — issue #98 版本戳，单一事实源。
 *
 * 在**每次 build 时刻**（`npm run build`/`lint`/`test`/`test:watch` 的前置步骤，见
 * `package.json`）把 `package.json` 的 `version` + 当前 git short SHA（+ 脏树标记）固化成
 * `src/shared/version-info.generated.ts`——这个生成文件**不进 git**（`.gitignore` 挡住），每次
 * 都重新生成，不依赖上一次残留的内容。
 *
 * 为什么在 build 时刻固化、不在运行时现算：全局安装（`install-global-brain.mjs`）把整个
 * `dist/` 拷进 `~/.claude/aeloop-brain/repo-snapshot/` 之后，那个目录**没有 `.git`**——任何
 * 运行时 `git rev-parse` 在那都会失败。`install-global-brain.mjs` 本来就会在拷贝前跑一次
 * `pnpm run build`（见该文件 `installGlobalBrain()`），这次 build 天然就是"装的时候固化"的
 * 那一刻，`dist/shared/version-info.generated.js` 会跟着 `dist/` 一起被拷走，运行时只读这个
 * 已经固化好的产物，不再碰 git（详见 `docs/version-stamping/PRD.md` §2.2）。
 *
 * fail-soft（issue #98 原文要求）：两次 git 调用（`rev-parse`/`status --porcelain`）各自独立
 * try/catch，git 不可用（非 git 目录、`git` 命令不存在、`.git` 损坏——例如从 `npm pack` 出的
 * tarball 解压后直接跑 `npm run build`）→ `gitSha = "unknown-sha"`、`gitDirty = false`，**绝不
 * 抛错、绝不让 build 因为拿不到 git 而失败**。
 *
 * 跑法：`node scripts/generate-version.mjs`（也可以直接 `node scripts/generate-version.mjs
 * --repo-root=<dir>` 指向别的仓库根，供 `test-generate-version.mjs` 在临时目录里驱动，不碰
 * 真实仓库自己的 `src/`）。
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const DEFAULT_REPO_ROOT = path.join(HERE, "..");

function defaultExecImpl(cmd, args, options) {
  return execFileSync(cmd, args, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], ...options });
}

/**
 * `execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: repoRoot })`，独立 try/catch
 * ——git 不可用（非 git 目录 / `git` 未安装 / `.git` 损坏）→ `"unknown-sha"`，不抛错。
 * @param {string} repoRoot
 * @param {(cmd: string, args: string[], options: object) => string} execImpl
 * @returns {string}
 */
export function resolveGitShortSha(repoRoot, execImpl = defaultExecImpl) {
  try {
    const sha = execImpl("git", ["rev-parse", "--short", "HEAD"], { cwd: repoRoot }).trim();
    return sha || "unknown-sha";
  } catch {
    return "unknown-sha";
  }
}

/**
 * `execFileSync("git", ["status", "--porcelain"], { cwd: repoRoot })`，独立 try/catch——git 不
 * 可用时无法判断脏不脏，统一按"不脏"处理（尽力而为的软信号，不是强承诺，见 PRD §2.2 step 3）。
 * @param {string} repoRoot
 * @param {(cmd: string, args: string[], options: object) => string} execImpl
 * @returns {boolean}
 */
export function resolveGitDirty(repoRoot, execImpl = defaultExecImpl) {
  try {
    const status = execImpl("git", ["status", "--porcelain"], { cwd: repoRoot });
    return status.trim().length > 0;
  } catch {
    return false;
  }
}

/**
 * issue #98 Zorro 独立复审(#2,准确性/覆盖缺口):此前只有**数据**（packageVersion/gitSha/
 * gitDirty）单源,**格式化**（`<packageVersion>+<gitSha>[-dirty]` 这条拼接规则）在
 * `src/shared/version.ts` / `docs/conductor-brain-layer/spike/lib/version-info.mjs` /
 * `scripts/install-global-brain.mjs` 三处各自重建一遍(后两者是 `.mjs`,物理上不能 `import`
 * `version.ts` 这个 `.ts` 文件)——三处拼接逻辑碰巧写得一致,但没有任何机制保证它们不会漂移。
 * 采纳军师建议的方案:把**格式化好的完整 `versionString`** 也在这里（生成的那一刻）算一次、
 * 写进生成产物,三面直接**读**这个字段,不再各自拼 `+`/`-dirty`。"四面一致"因此变成物理保证
 * （同一个字符串字面量,不是三份独立实现巧合算出同一个结果),不是靠人工保持三处同步。
 * @param {{ packageVersion: string, gitSha: string, gitDirty: boolean }} parts
 * @returns {string}
 */
export function formatVersionString({ packageVersion, gitSha, gitDirty }) {
  return `${packageVersion}+${gitSha}${gitDirty ? "-dirty" : ""}`;
}

/**
 * 纯函数——给定 repoRoot（含 `package.json`）算出完整的版本信息对象。不做任何文件写入，
 * 供 `test-generate-version.mjs` 直接对返回值做断言。
 * @param {{ repoRoot: string, execImpl?: (cmd: string, args: string[], options: object) => string }} opts
 * @returns {{ packageVersion: string, gitSha: string, gitDirty: boolean, versionString: string, generatedAt: string }}
 */
export function computeVersionInfo({ repoRoot, execImpl = defaultExecImpl }) {
  const pkg = JSON.parse(readFileSync(path.join(repoRoot, "package.json"), "utf8"));
  if (typeof pkg.version !== "string" || pkg.version.trim() === "") {
    throw new TypeError(`${path.join(repoRoot, "package.json")} 缺少非空的 "version" 字段`);
  }
  const packageVersion = pkg.version;
  const gitSha = resolveGitShortSha(repoRoot, execImpl);
  const gitDirty = resolveGitDirty(repoRoot, execImpl);
  return {
    packageVersion,
    gitSha,
    gitDirty,
    versionString: formatVersionString({ packageVersion, gitSha, gitDirty }),
    generatedAt: new Date().toISOString(),
  };
}

/**
 * @param {{ packageVersion: string, gitSha: string, gitDirty: boolean, versionString: string, generatedAt: string }} info
 * @returns {string}
 */
export function renderGeneratedModule(info) {
  return `// GENERATED by scripts/generate-version.mjs — 不要手改，不要 commit（.gitignore 挡住）。
// 每次 \`npm run build\`/\`lint\`/\`test\`/\`test:watch\` 都会重新生成，见 docs/version-stamping/PRD.md §2.3。
//
// gitDirty 是"尽力而为"的软信号：git 不可用（非 git 目录 / tarball 安装）时统一按 false 处理，
// 不代表"确认干净"——见 scripts/generate-version.mjs 的 resolveGitDirty() 头注释。
//
// versionString 是**唯一的格式化真源**（issue #98 Zorro 复审 #2）：packageVersion/gitSha/
// gitDirty 三个原始字段单独保留是为了需要拆开读的场景（如 EvidenceBundle 未来可能想单独查
// gitDirty），但 "<packageVersion>+<gitSha>[-dirty]" 这条拼接规则只在这里算一次——每一处
// 展示版本号的地方（CLI --version / EvidenceBundle.engineVersion / wake-greeting 版本行 /
// 全局安装回显）都应该直接读这个字段，不要自己再拼一遍 "+"/"-dirty"。

export interface GeneratedVersionInfo {
  readonly packageVersion: string;
  readonly gitSha: string;
  readonly gitDirty: boolean;
  readonly versionString: string;
  readonly generatedAt: string;
}

export const GENERATED_VERSION_INFO: GeneratedVersionInfo = ${JSON.stringify(info, null, 2)};
`;
}

/**
 * @param {{ repoRoot?: string, outFile?: string, execImpl?: (cmd: string, args: string[], options: object) => string }} [opts]
 * @returns {{ outFile: string, info: ReturnType<typeof computeVersionInfo> }}
 */
export function generateVersionFile(opts = {}) {
  const { repoRoot = DEFAULT_REPO_ROOT, execImpl = defaultExecImpl } = opts;
  const outFile = opts.outFile ?? path.join(repoRoot, "src", "shared", "version-info.generated.ts");
  const info = computeVersionInfo({ repoRoot, execImpl });
  mkdirSync(path.dirname(outFile), { recursive: true });
  writeFileSync(outFile, renderGeneratedModule(info));
  return { outFile, info };
}

function parseArgs(argv) {
  const opts = {};
  for (const arg of argv) {
    if (arg.startsWith("--repo-root=")) opts.repoRoot = arg.slice("--repo-root=".length);
  }
  return opts;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { repoRoot } = parseArgs(process.argv.slice(2));
  const { outFile, info } = generateVersionFile(repoRoot ? { repoRoot } : {});
  console.log(`[generate-version] 写入 ${outFile}`);
  console.log(`  packageVersion: ${info.packageVersion}`);
  console.log(`  gitSha: ${info.gitSha}`);
  console.log(`  gitDirty: ${info.gitDirty}`);
}
